# When enable you agree to send your environment data to plugin authors
Reporter:
  enabled: true
  data:
    core: true
    plugins: true

EventsLogger:
  enabled: false
  log:
  - Event
  - PlayerMoveEvent:20
  - -EntityEvent
  - -WorldEvent
