# When enable you agree to send your environment data to plugin authors
Reporter:
  enabled: true
  data:
    core: true
    plugins: true

EventsLogger:
  enabled: false
  hierarchy: true
  log:
  - Event
  - PlayerStatisticIncrementEvent:100
  - PlayerMoveEvent:20
  - -ChunkEvent
  - -BlockEvent
  - -VehicleEvent
  - -EntityAirChangeEvent

PacketsLogger:
  enabled: false
  log:
  - Handshake
  - Play
  - Status
  - Login
